apiVersion: apps/v1
kind: Deployment
metadata:
  name: armory-agent
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "spinnaker"
        vault.hashicorp.com/agent-inject-secret-armory-agent-local.yml: ""
        vault.hashicorp.com/secret-volume-path-armory-agent-local.yml: '/opt/armory/config'
        vault.hashicorp.com/agent-inject-file-armory-agent-local.yml: 'armory-agent.yml'
        vault.hashicorp.com/agent-inject-template-armory-agent-local.yml: |
          kubernetes:
            accounts:
          {{- with secret "secret/kubeconfig" -}}
          {{ range $k, $v := .Data.data }}
              - kubeconfigFile: 'encryptedFile:vault!e:secret!n:kubeconfig!k:{{ $k }}'
                name: {{ $k -}}
          {{- else }}
              []
          {{ end -}}
          {{- end }}
          secrets:
            vault:
              enabled: true
              authMethod: KUBERNETES
              role: spinnaker
              path: kubernetes
              url: http://10.100.146.32:8200
          clouddriver:
            insecure: true
    spec:
      volumes:
        - $patch: delete
          name: volume-armory-agent-config
        - $patch: delete
          name: volume-armory-agent-kubeconfigs
      containers:
        - name: agent
          volumeMounts:
            - $patch: delete
              name: volume-armory-agent-config
              mountPath: /opt/armory/config
            - $patch: delete
              name: volume-armory-agent-kubeconfigs
              mounthPath:
              mountPath: /kubeconfigfiles